### ISSUE TITLE
Pressing enter key on 10-key clears the display

### ISSUE THREAD

**Issue by darman12** [matchewbie/calculator#1]
This occurs in Google Chrome Version 70.0.3904.70 (64-bit) on MacOS 10.15.

Does not happen in Safari or Firefox Developer Addition.

**Comment by matchewbie** [comment]
Interesting!

I'm having no issue in Chrome 78 on MacOS 10.13, but the KeyboardEvent.**key** _shouldn't_ cause any issues on Chrome 70... it's been a supported attribute since Chrome 51. I did just read that the **key** attribute for Enter can also sometimes be "Return", so I've added that as a case.

I want to make sure the event isn't triggering my clearAll function somehow before diving deeper. Would you mind checking it out again in Chrome with the JavaScript Console open? I just pushed a new commit to log the keydown/keyup events to the console. Just a heads up that it'll log both, so you'll have duplicates (hopefully!). I'm curious to hear what it's logging when this issue is happening!

edit:

Adding a log in clearAll() that _should_ only be triggered by the C html-button's onclick, the 'c' key, or the 'Clear' key on Mac... which is what pressing Num Lock on Mac also fires as it's **key** attribute.

**Comment by matchewbie** [comment]
Added Enter/Return to be included for **preventDefault()** just in case it was _clearing_ by adding a newline. Also, I think one of the first things that I changed last night (that I forgot to tell you) was the listeners being on the document instead of the window. I read that it's not best practice to have them on the window, and that some interference can occur.

**Comment by darman12** [comment]
Hey! You fixed the issue :) I haven't taken a look at your code (because I haven't finished mine yet) so I don't have any feedback or input in regards to the changes you made.

I like the UI, by the way. The animations and menu are really good 👍

**Comment by matchewbie** [comment]
Awesome! And thanks!

I'm guessing the issue wasn't the value of the event's key attribute, but probably had to do with having the listener on the window (instead of document) leading to funkiness in Chrome. So yeah... don't do what I did there.

I'll definitely be coming back to this project to update it as I learn more. By the way, thanks for raising the issue, debugging it was a nice break from the Rails project I've been working on.

Looking forward to playing with your implementation. I like what you did with your Etch-A-Sketch!
